modLoader="javafml"
loaderVersion="[39,)"
license="Apache-2.0"
issueTrackerURL="https://github.com/LXGaming/NorthernCompass/issues"

[[mods]]
modId="northerncompass"
version="${version}"
displayName="NorthernCompass"
displayURL="https://www.curseforge.com/minecraft/mc-mods/northerncompass"
logoFile="lxgaming.png"
credits="LX_Gaming"
authors="LX_Gaming"
description="""
Source: https://github.com/LXGaming/NorthernCompass
"""